### ISSUE TITLE
can't find crate for `alloc`

### ISSUE THREAD

**Issue by l3gacyb3ta** [ayrtonm/psx-sdk-rs#34]
I'm trying to build one of the demos, but it keeps giving me an issue with building it?

```rust_error
error[E0463]: can't find crate for `alloc`
  --> src/main.rs:13:1
   |
13 | psx::sys_heap!(4 kb);
   | ^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = note: this error originates in the macro `$crate::sys_heap` which comes from the expansion of the macro `psx::sys_heap` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by l3gacyb3ta** [comment]
Oh also, sort_by_key seems to be broken?
```rust
error[E0599]: no method named `sort_by_key` found for array `[(Face, Color); 500]` in the current scope
   --> src/main.rs:142:19
    |
142 |             faces.sort_by_key(|(face, _)| {
    |             ------^^^^^^^^^^^
    |
    ```

**Comment by ayrtonm** [comment]
Hello! Both issues sound like `cargo-psx` is missing the `alloc` in `-Zbuild-std=core,alloc`. Older versions and I think the default one from crates.io didn't do this. Can you retry by first uninstalling cargo-psx and installing it from the main branch of this repo (instructions in readme)? I'll try to update the crates.io version in a few days.

**Comment by l3gacyb3ta** [comment]
Aha! That seems to have worked

**Comment by ayrtonm** [comment]
Closing this as I pushed an updated version of cargo-psx to crates.io today.
