### ISSUE TITLE
CD-ROM reads are forced to word alignment

### ISSUE THREAD

**Issue by SolraBizna** [ayrtonm/psx-sdk-rs#5]
I've noticed that if you call the `file_read` function (directly or indirectly through `File`) on a CD-ROM file, and you pass in a buffer that isn't word-aligned, the low 2 bits of the address are ignored. I suspect that this is because the BIOS uses DMA to write into the buffer, and the DMA engine ignores the low 2 bits of addresses. I don't know if this also applies to memory card file reads. (I *assume* it doesn't apply to TTY reads...)

I don't think there is a good way to safe this. Detecting and panicking on non-word-aligned reads seems like it would be a terrible solution, but at least it prevents memory corruption and is simple. Bumping the pointer up to the next word-aligned address and sliding backwards by 1-3 bytes after return, if there's room, wouldn't be too bad... but requires knowledge of the block size, and handling the edge case where an exact number of blocks are being read and therefore it has to be done in two reads... and it writes up to 3 bytes past the returned "number of bytes read" value, which might be surprising... and requires a separate solution if exactly *one* block is being read... and all that makes the wrapper pretty non-trivial. And either solution will be bad if one is reading from a type of `File` that doesn't suffer from this problem...

**Comment by ayrtonm** [comment]
Nice catch! I hadn't realized this was an issue. I see two or three possible solutions here

- change `dst` to `&mut [u32]`
- use the [aligned crate](https://crates.io/crates/aligned) and change `dst` to `&mut Aligned<A4, [u8; N]>`

I think there's a third solution for using `Aligned` without the compile-time buffer size, but it's very ugly. `Aligned` is zero-cost, but I think working with `Aligned` boilerplate is more cumbersome than casting `&mut [u32]` to a `&mut [u8]` or whatever struct you're reading from disk. I'm leaning heavily towards option 1.

**Comment by SolraBizna** [comment]
`Aligned` is clearer, I think, especially since you can *read* a non-multiple-of-four number of bytes and—whoah, uh, let me check that before I say anything else... (if I've learned one thing about the PSX BIOS it's that you can't assume *anything*.)

Well, if non-multiple-of-four-byte-reads work, I think we should use `Aligned`, since it's more clear about the reason for the unusual parameter type. BIOS IO on a PlayStation is low enough level that the extra boilerplate won't be too burdensome. I think. But if the test I'm about to do shows that it always writes a multiple of four bytes, then we should make it `&mut [u32]` because that would be what it actually is.

I'll run a test and comment again with the results.

**Comment by SolraBizna** [comment]
Ack, what was I thinking? Of course a non-multiple-of-four read won't work, because it *definitely* won't be a multiple of the sector size...

Yes, I say go with `&mut [u32]`. It won't work right with `tty` devices and the like but nobody sane will be using the BIOS block IO routines to do that anyway. Just make sure to nail down whether the return value is a byte count or a word count.

**Comment by ayrtonm** [comment]
> It won't work right with tty devices

I mean you said the issue was with CDs right? I think it should be straightforward to make a `read` specifically for CD files and another for memcard/tty since `File` is parameterized by `FileTy`

**Comment by SolraBizna** [comment]
Do you know if memcard devices suffer from the alignment problem? (I'm not currently set up to test that...)

**Comment by ayrtonm** [comment]
Don't know, but I'd guess they do.

**Comment by SolraBizna** [comment]
Then I'd say, just go with `&mut [u32]` for all Files. It may be necessary to use `&[u32]` for writes as well, depending. Since most emulators don't support TTY reads, and using the TTY device on a real PlayStation requires soldering and/or addon hardware... I think it's okay not to actively support it in the SDK. Somebody who wants to use the TTY device in their Rust program has the option of using the BIOS routines directly; and then they will almost certainly want to use `getchar` and friends rather than `read`/`write` anyway.
